
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - menu
      - order
      - customer
      - inventory
      - payment

  menu:
    build: ./menu-services
    ports:
      - "3001:3001"

  order:
    build: ./order-services
    ports:
      - "3002:3002"

  inventory:
    build: ./inventory-services
    ports:
      - "3004:3004"

  customer:
    build: ./customer-services
    ports:
      - "3005:3005"

  payment:
    build: ./payment-services
    ports:
      - "3003:3003"
