name: Build and Push Docker Images

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push API Gateway
        uses: docker/build-push-action@v4
        with:
          context: ./api-gateway
          push: true

      - name: Build and push Menu Service
        uses: docker/build-push-action@v4
        with:
          context: ./menu-services
          push: true

      - name: Build and push Order Service
        uses: docker/build-push-action@v4
        with:
          context: ./order-services
          push: true

      - name: Build and push Inventory Service
        uses: docker/build-push-action@v4
        with:
          context: ./inventory-services
          push: true

      - name: Build and push Customer Service
        uses: docker/build-push-action@v4
        with:
          context: ./customer-services
          push: true

      - name: Build and push Payment Service
        uses: docker/build-push-action@v4
        with:
          context: ./payment-services
          push: true
